#!/usr/bin/env python3

from pathlib import Path
from sys import argv
import re

def canvas_roster_to_text(fn):
    tempfn = 'new___' + fn
    with open(fn, 'r') as ifile:
        with open(tempfn, 'w') as ofile:
            for line in ifile:
                if line.find('\t') >= 0 and line.find('Jason Shepherd') == -1:
                    pieces = line.split('\t')
                    if len(pieces) >= 3:
                        ofile.write('%s,%s\n'
                            % (pieces[1].rstrip(), pieces[2].rstrip()))
    Path(fn).unlink()
    #Path(tempfn).rename(fn)
    Path(tempfn).rename('roster.csv')

progname = Path(argv[0]).stem

if len(argv) != 2:
    print('Usage: %s <canvas-roster-text-file>' % progname)
    exit(1)

filename = argv[1]

if not Path(filename).exists():
    print('No such file ' + filename)
    exit(2)

canvas_roster_to_text(filename)

