#!/bin/bash

if [[ $# -ne 1 ]]; then
  echo "Usage: $0 <pyfile.py>"
  exit 1
fi

if [[ ! -e $1 ]]; then
  echo "Wrong filename."
  exit 1
fi

export FLASK_APP=$1
if [[ -z "${FLASK_PORT}" ]]; then
  echo "WARNING: FLASK_PORT undefined.  Using 5000 as default."
  flask run --host=0.0.0.0 --port=5000
else
  flask run --host=0.0.0.0 --port=$FLASK_PORT
fi
