#!/bin/bash

python3 -m venv env

if [[ ! -e .env ]]; then
cat >.env <<ENV_EOF
source env/bin/activate
export FLASK_PORT=5000
export FLASK_ENV=development
ENV_EOF
fi

source .env
pip install Flask
pip install Flask-SQLAlchemy
pip install requests

echo "----------------------------"
echo "'env' created. You may now:"
echo "source .env"
