#!/bin/bash

if [[ $# -eq 0 ]] ; then
    echo "Usage: $(basename $BASH_SOURCE) [fileprefix ...]"
    exit 1
fi

for prefix in "$@"; do
    if [[ -e $prefix.html ]]; then
        echo "$prefix.html already exists!"
        exit 2
    fi
done

for prefix in "$@"; do
    cat >$prefix.html <<EOF
<!doctype html>
<html>

<head>
  <title>$prefix</title>

  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
</head>

<body>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
<!-- UNCOMMENT FOR REACT
  <script src="https://unpkg.com/react@18/umd/react.development.js"></script>
  <script src="https://unpkg.com/react-dom@18/umd/react-dom.development.js"></script>
  <script src="https://unpkg.com/@babel/standalone/babel.min.js"></script>
  <script type="text/babel" src="your-script-here.js"></script>
-->

</body>

</html>
EOF
done

